In [1]:
%timeit [j**4 for j in range(1,9)]

945 ns ± 37.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
import numpy  as np

%timeit np.arange(1,9)**4

2.67 μs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array

In [3]:
import numpy as np
a=[1,2,3,4,5,6]
b= np.array(a)
print(b)
print(type(b))
print(b.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [20]:
l=[]

for i in range(1,5):
    a=int(input("Enter:"))
    l.append(a)

print(np.array(l))

Enter: 4
Enter: 3
Enter: 2
Enter: 2


[4 3 2 2]


In [9]:
a2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(a2)
print(a2.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]]
2


In [21]:
a3=np.array([[[1,2,3,4],[1,2,3,4],[5,6,7,8]]])
print(a3)
print(a3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [5 6 7 8]]]
3


In [31]:
ar=np.array([1,2,3,4,5], ndmin=10)
print(ar)
print(ar.ndim)


[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


# Zeros

In [34]:
import numpy as np

In [36]:
a_zero= np.zeros(4)
print(a_zero)

[0. 0. 0. 0.]


In [46]:
a_zero= np.zeros(4)
a_zero1=np.zeros((3,4))
print(a_zero)
print()
print(a_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [49]:
a_one = np.ones(3)
print(a_one)

[1. 1. 1.]


# Empty

In [52]:
ar_em=np.empty(4)
print(ar_em)

[0. 0. 0. 0.]


# Range

In [57]:
ar_rn= np.arange(4)
print(ar_rn)

[0 1 2 3]


# Diag

In [60]:
ar_dia = np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [62]:
ar_dia = np.eye(4,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


# linspace

In [65]:
ar_ln = np.linspace(1,10,num=5)
print(ar_ln)


[ 1.    3.25  5.5   7.75 10.  ]


In [69]:
ar_ln = np.linspace(0,10,num=5)
print(ar_ln)

[ 0.   2.5  5.   7.5 10. ]


In [71]:
ar_ln = np.linspace(0,20,num=5)
print(ar_ln)

[ 0.  5. 10. 15. 20.]
