In [5]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [9]:
a=np.array((1,2,3,4))
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [11]:
arr1 = np.array([2, 3, 2+4j, 5, 6.5]) # complex
arr1

array([2. +0.j, 3. +0.j, 2. +4.j, 5. +0.j, 6.5+0.j])

In [13]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
a=np.array([1,2,3,4.5,5])
a

array([1. , 2. , 3. , 4.5, 5. ])

In [17]:
a=np.array([1,2,3,4+3j,5])
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+3.j, 5.+0.j])

In [19]:
a=np.array([1,2,3,4,5,"python"])
a

array(['1', '2', '3', '4', '5', 'python'], dtype='<U11')

In [23]:
a=np.array([1,2,3,4,5] ,dtype="float")
a

array([1., 2., 3., 4., 5.])

In [25]:
a=np.array([1,2,3,4,5] ,dtype="complex")
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [29]:
a=np.array([1.2,2.4,4.5,6.7],dtype="int")
a

array([1, 2, 4, 6])

In [31]:
a=np.array([1.2,2.4,4.5,6.7],dtype="complex")
a

array([1.2+0.j, 2.4+0.j, 4.5+0.j, 6.7+0.j])

In [33]:
a=np.array([1.2+0.j, 2.4+0.j, 4.5+0.j, 6.7+0.j],dtype="int")
a

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [35]:
a=np.array([1.2+0.j, 2.4+0.j, 4.5+0.j, 6.7+0.j],dtype="float")
a

TypeError: float() argument must be a string or a real number, not 'complex'

In [37]:
a0=np.array(23)
print(a0)
print("dimension of array is:",a0.ndim)

23
dimension of array is: 0


In [39]:
a0=np.array("shreya")
print(a0)
print("dimension of array is:",a0.ndim)

shreya
dimension of array is: 0


In [41]:
a1=np.array([1,2,3,4,5])
print(a1)
print("dimesion of array is:",a1.ndim)

[1 2 3 4 5]
dimesion of array is: 1


In [53]:
a1=np.array((1,2,3,4))
print(a1)
print("dimesion of array is:",a1.ndim)

[1 2 3 4]
dimesion of array is: 1


In [45]:
arr = np.array([54.654, 654.555, 4.48, 5.488])
print(arr)
print("Dimension of array is:", arr.ndim)

[ 54.654 654.555   4.48    5.488]
Dimension of array is: 1


In [47]:
arr = np.array((2))
print(arr)
print("Dimension of array is:", arr.ndim)

2
Dimension of array is: 0


In [59]:
arr=np.array([1,2])
print(arr)
print("Dimesion o array is :",arr.ndim)
print(arr.shape)

[1 2]
Dimesion o array is : 1
(2,)


In [63]:
a2=np.array([[2,3],[1,4],[8,6]])
print(a2)
print("Dimesion of array is :",a2.ndim)
print(a2.shape)

[[2 3]
 [1 4]
 [8 6]]
Dimesion of array is : 2
(3, 2)


In [67]:
arr2=np.array(((2,3,4,5,7,6,5,4)))
print(arr2)
print("Dimesion of aaray is :",arr2.ndim)
print(arr2.shape)

[2 3 4 5 7 6 5 4]
Dimesion of aaray is : 1
(8,)


In [69]:
arr3=np.array([[[1,2,3,4,5,6]]])
print("Dimesion of array is:",arr3.ndim)
print(arr3.shape)

Dimesion of array is: 3
(1, 1, 6)


In [73]:
arr3=np.array([[[1,2,3],[4,5,6],[4,5,67]]])
print("Dimesion of array is:",arr3.ndim)
print(arr3.shape)

Dimesion of array is: 3
(1, 3, 3)


In [75]:
arr3 = np.array([[[2,3], [3,4], [8,7]], [[12,13], [13,14], [18,17]], [[120,130], [130,140], [180,170]]])
print(arr3)
print("Dimensions of array are:", arr3.ndim)
print(arr3.shape)

[[[  2   3]
  [  3   4]
  [  8   7]]

 [[ 12  13]
  [ 13  14]
  [ 18  17]]

 [[120 130]
  [130 140]
  [180 170]]]
Dimensions of array are: 3
(3, 3, 2)


In [77]:
a3=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,7,6]],[[4,5,6],[2,3,4]]])
print(a3)
print("Dimension of array is :",a3.ndim)
print(a3.shape)

[[[1 2 3]
  [3 4 5]]

 [[6 7 8]
  [9 7 6]]

 [[4 5 6]
  [2 3 4]]]
Dimension of array is : 3
(3, 2, 3)


In [79]:
# 4-D array >> 4 square brackets

arr4 = np.array([[[[2,1,4,5,7,8]]]])
print(arr4)
print("Dimensions of array are:", arr4.ndim)
print(arr4.shape)

[[[[2 1 4 5 7 8]]]]
Dimensions of array are: 4
(1, 1, 1, 6)


In [83]:
a1=np.array([1,2,4,3],ndmin=8)
print(a1)
print("Dimesion of array is :",a1.ndim)

[[[[[[[[1 2 4 3]]]]]]]]
Dimesion of array is : 8


In [93]:
arr1 = np.array([4,5,7,8,9,7])
arr1[:3]

array([4, 5, 7])

In [95]:
arr1 = np.array([4,5,7,8,9,7])  # 0 1 2
arr1[2:5] 

array([7, 8, 9])

In [97]:
arr1 = np.array([4,5,7,8,9,7])  # 0 1 2
arr1[1:5] 

array([5, 7, 8, 9])

In [99]:
arr1 = np.array([4,5,7,8,9,7])  # 0 1 2
arr1[2:4] 

array([7, 8])

In [101]:
arr1 = np.array([4,5,7,8,9,7]) 
arr1[::-1]

array([7, 9, 8, 7, 5, 4])

In [107]:
arr1 = np.array([4,5,7,8,9,7,3,2,2,1])  # 0 1 2
arr1[3:9]

array([8, 9, 7, 3, 2, 2])

In [109]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2

array([[4, 5],
       [9, 7],
       [8, 6]])

In [111]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2[0]

array([4, 5])

In [113]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2[1]

array([9, 7])

In [115]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2[2]

array([8, 6])

In [119]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2[0][0] 

4

In [121]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2[0][1] 

5

In [123]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2[1][0] 

9

In [125]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2[1][1] 

7

In [127]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2[2][0] 

8

In [129]:
arr2 = np.array([[4,5], [9,7], [8,6]])
arr2[2][1] 

6

In [131]:
arr2 = np.array([[4,5,8], [9,7,3], [8,6,2]])
print(arr2)
arr2.shape

[[4 5 8]
 [9 7 3]
 [8 6 2]]


(3, 3)

In [133]:
arr2 = np.array([[4,5,8], [9,7,3], [8,6,2]])
arr2[:,:]

array([[4, 5, 8],
       [9, 7, 3],
       [8, 6, 2]])

In [143]:
arr2 = np.array([[4,5,8], [9,7,3], [8,6,2]])
arr2[1:3,:2]  # all the rows and 1st 2 columns

array([[9, 7],
       [8, 6]])

In [ ]:
arr2 = np.array([[4,5,8], [9,7,3], [8,6,2]])
arr2[:,:2]  # all the rows and 1st 2 columns