In [79]:
 import numpy as np
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [81]:
arr=np.zeros(5,dtype="float")
arr

array([0., 0., 0., 0., 0.])

In [83]:
arr=np.zeros(5,dtype="int")
arr

array([0, 0, 0, 0, 0])

In [85]:
arr=np.zeros([2,3],dtype="float")
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [87]:
arr=np.zeros([3,2],dtype="float")
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [89]:
arr=np.zeros([2,2],dtype="float")
arr

array([[0., 0.],
       [0., 0.]])

In [91]:
arr=np.zeros([3,3],dtype="float")
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [95]:
arr_ones=np.ones([5],dtype="int")
arr_ones

array([1, 1, 1, 1, 1])

In [97]:
arr_ones=np.ones([5],dtype="float")
arr_ones

array([1., 1., 1., 1., 1.])

In [99]:
arr_ones=np.ones([5,3],dtype="int")
arr_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [101]:
arr_ones=np.ones([2,3],dtype="int")
arr_ones

array([[1, 1, 1],
       [1, 1, 1]])

In [103]:
arr_ones=np.ones([3,3],dtype="int")
arr_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [105]:
arr_ones=np.ones([2,4],dtype="float")
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [107]:
import pandas as pd
a=pd.DataFrame(arr_ones)
a

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0

In [109]:
b=pd.DataFrame(arr)
b

0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0

In [111]:
arr=np.arange(20,10,-1)
arr

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [113]:
arr.reshape(2,5)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11]])

In [115]:
arr.reshape(5,2)

array([[20, 19],
       [18, 17],
       [16, 15],
       [14, 13],
       [12, 11]])

In [117]:
arr=np.empty([2,2],dtype=int)
print(arr)

[[4 4]
 [4 4]]


In [119]:
arr=np.empty([3,2],dtype=int)
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [195]:
arr=np.full([2,2],3)
print(arr)

[[3 3]
 [3 3]]


In [197]:
arr=np.full([2,2],4)
print(arr)

[[4 4]
 [4 4]]


In [199]:
arr=np.full([3,3],2)
print(arr)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [201]:
arr=np.linspace(1,20,num=10)
arr

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [203]:
arr=np.linspace(1,50,num=10)
arr

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [205]:
s={"zeros": np.zeros(10),
   "Ones": np.ones(10),
   "Arange":np.arange(10,21),
   "Linspace":np.linspace(100,200,num=25)}
s

{'zeros': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'Ones': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'Arange': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 'Linspace': array([100.        , 104.16666667, 108.33333333, 112.5       ,
        116.66666667, 120.83333333, 125.        , 129.16666667,
        133.33333333, 137.5       , 141.66666667, 145.83333333,
        150.        , 154.16666667, 158.33333333, 162.5       ,
        166.66666667, 170.83333333, 175.        , 179.16666667,
        183.33333333, 187.5       , 191.66666667, 195.83333333,
        200.        ])}

In [207]:
dict_rounded={key:np.round(value,2) for key,value in s.items()}
dict_rounded

{'zeros': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'Ones': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'Arange': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 'Linspace': array([100.  , 104.17, 108.33, 112.5 , 116.67, 120.83, 125.  , 129.17,
        133.33, 137.5 , 141.67, 145.83, 150.  , 154.17, 158.33, 162.5 ,
        166.67, 170.83, 175.  , 179.17, 183.33, 187.5 , 191.67, 195.83,
        200.  ])}

In [209]:
np.eye(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [211]:
np.eye(2,3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0]])

In [213]:
np.eye(2,3,dtype="float")

array([[1., 0., 0.],
       [0., 1., 0.]])

In [215]:
np.eye(5,4,k=2,dtype="int")

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [219]:
np.identity(5,dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [217]:
np.identity(3,dtype="float")

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [221]:
np.eye(4,3,k=2,dtype="float")

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Random

# Rand()

In [223]:
import numpy as np

In [225]:
a = np.random.rand(5,4)

In [227]:
a

array([[0.72175872, 0.91174837, 0.70004402, 0.91716088],
       [0.60826515, 0.51743389, 0.78147491, 0.4892779 ],
       [0.07059604, 0.37028596, 0.59644649, 0.76097761],
       [0.81412994, 0.36276527, 0.53050958, 0.96174472],
       [0.7902179 , 0.06572361, 0.25853158, 0.21368488]])

In [229]:
a = np.random.rand(5)
a

array([0.19290541, 0.79998872, 0.70070574, 0.97397261, 0.39970919])

In [231]:
a = np.random.rand(2,3)
a

array([[0.77163558, 0.4914655 , 0.39134935],
       [0.28421974, 0.42506446, 0.62648372]])

In [233]:
a = np.random.rand(4,2)
a

array([[0.77284956, 0.06572658],
       [0.06351545, 0.56715373],
       [0.77480272, 0.58433679],
       [0.9688587 , 0.45929084]])

# Randn

In [235]:
a=np.random.randn(2,3)
a

array([[-0.35630263, -0.92206323,  1.93203794],
       [ 0.40786221,  0.4678339 , -0.50290678]])

In [237]:
a=np.random.randn(5)
a

array([-0.26420721,  0.18695161,  0.69560422, -1.02102922, -0.2887595 ])

# Ranf

In [239]:
a=np.random.ranf(4)
a


array([0.84876013, 0.57688045, 0.77409863, 0.89012226])

# randint()

In [241]:
a=np.random.randint(5,20,5)
a

array([16,  6, 11,  9, 16])

In [243]:
a=np.random.rand(3)
a

array([0.86091388, 0.52075201, 0.10615199])

In [245]:
a=np.random.rand(3,2)
a

array([[0.69951943, 0.71537567],
       [0.35115556, 0.48817057],
       [0.95681325, 0.03552727]])

In [247]:
a=np.random.rand(4,2)
a

array([[0.82458123, 0.23259583],
       [0.62413428, 0.79766868],
       [0.25997841, 0.4382139 ],
       [0.77476334, 0.04192357]])

In [249]:
a=np.random.rand(3,3)
a

array([[0.99489201, 0.59755784, 0.75924968],
       [0.12093042, 0.02314671, 0.69408965],
       [0.82817595, 0.21649044, 0.20627573]])

In [251]:
a=np.random.randint(9,29,size=5,dtype="int")
a

array([19, 16, 20, 26, 11])

In [253]:
a=np.random.randint(9,29,size=(5,5),dtype="int")
a

array([[15, 10, 28, 19, 15],
       [17, 26, 24, 22, 14],
       [16,  9, 21, 21, 23],
       [24, 22,  9, 14, 15],
       [22,  9, 13, 17,  9]])

In [255]:
a=np.random.randint(4,9,size=(5,5),dtype="int")
a

array([[4, 4, 4, 8, 7],
       [4, 5, 8, 4, 8],
       [6, 6, 6, 4, 6],
       [5, 4, 4, 8, 8],
       [7, 7, 6, 7, 7]])

In [257]:
a=np.random.randint(4,9,size=(5,5,4),dtype="int")
a

array([[[5, 6, 4, 4],
        [8, 7, 4, 7],
        [7, 6, 8, 5],
        [7, 6, 5, 7],
        [8, 4, 7, 8]],

       [[8, 6, 4, 4],
        [7, 5, 6, 6],
        [8, 5, 7, 5],
        [4, 4, 5, 7],
        [6, 6, 4, 5]],

       [[8, 6, 4, 4],
        [7, 6, 6, 8],
        [7, 4, 5, 4],
        [6, 5, 4, 4],
        [4, 8, 7, 5]],

       [[5, 7, 8, 5],
        [6, 4, 8, 5],
        [5, 6, 4, 7],
        [8, 4, 4, 7],
        [6, 5, 7, 5]],

       [[6, 7, 4, 6],
        [6, 6, 5, 4],
        [5, 8, 4, 7],
        [5, 7, 8, 7],
        [4, 5, 5, 6]]])

In [259]:
np.random.randn(5)

array([ 0.57720511, -0.42964687, -0.90375535,  0.73217761, -1.76247252])

In [261]:
np.random.randn(4,5)

array([[-0.862073  ,  0.83535157,  0.4186843 , -1.26553267, -0.15714877],
       [-0.01733157,  0.68755052, -0.23035115,  0.48831468,  0.41120252],
       [ 0.21465274,  0.45404124,  1.89089856, -0.605854  ,  0.88009699],
       [ 1.61150423,  0.2509527 , -0.14225364,  1.38995447,  0.77164849]])

In [263]:
np.random.randn(4,5,2)

array([[[ 0.77178533,  0.23865787],
        [ 1.89896638, -0.29792345],
        [-0.82872925, -0.15458216],
        [-0.62583896,  0.30919184],
        [-1.18054565,  1.25907691]],

       [[-0.45655379,  0.25871688],
        [-0.36097418, -0.06765422],
        [-1.02209333, -0.55543087],
        [-1.3764251 , -1.39919007],
        [ 0.76852607,  1.04043993]],

       [[ 0.98572023, -0.41575302],
        [ 0.29399888, -0.04809599],
        [-0.45484545,  0.83791938],
        [-0.01503375,  0.84490135],
        [ 0.88395104,  0.92983562]],

       [[-0.41803566,  0.45021901],
        [ 1.18195118, -1.16697142],
        [-1.8530296 , -0.19147445],
        [-0.23418253, -0.22292495],
        [ 0.06942935,  0.89897611]]])

In [265]:
np.random.ranf(3)


array([0.54836866, 0.91262166, 0.87002713])

In [267]:
np.random.random_sample((3,5))


array([[0.34786688, 0.14292343, 0.78020863, 0.23333054, 0.5567714 ],
       [0.06851041, 0.52929735, 0.60758653, 0.33445375, 0.14229452],
       [0.17972577, 0.0120761 , 0.7284204 , 0.19040665, 0.7428719 ]])

In [269]:
a=np.random.rand(5,6)
a

array([[0.72921562, 0.39345806, 0.37015762, 0.62139753, 0.34100129,
        0.37693277],
       [0.37746551, 0.84522382, 0.8634941 , 0.88398934, 0.42096196,
        0.4576309 ],
       [0.17462573, 0.62197127, 0.9536051 , 0.70153545, 0.99269049,
        0.12664971],
       [0.67893489, 0.52073539, 0.40718431, 0.9105634 , 0.08390408,
        0.88086153],
       [0.008049  , 0.89470556, 0.95943514, 0.18734365, 0.24827585,
        0.68817689]])

In [271]:
a=np.random.randn(3,5)
a

array([[ 0.72364219, -0.92772945, -0.07307404, -0.38506349, -0.19443383],
       [ 0.90091084, -0.67042699,  1.53321787, -1.83382592, -1.15340015],
       [-1.63850045, -0.32721766, -1.06006644, -0.28288868,  2.22467215]])

In [273]:
a=np.random.ranf(3)
a

array([0.23351053, 0.62443396, 0.65139222])

In [275]:
a=np.random.random_sample((3,6))
a

array([[0.40481956, 0.84123595, 0.87310823, 0.70508165, 0.53692116,
        0.10387161],
       [0.5985504 , 0.95356994, 0.92563502, 0.87856979, 0.34898627,
        0.83258611],
       [0.53015739, 0.23414392, 0.49963762, 0.82033158, 0.39130431,
        0.29514077]])

In [277]:
a=np.random.randint(8,20,size=9)
a

array([19, 14,  9, 18, 18, 15, 19, 14, 18])

In [279]:
a=np.random.randint(10,30,size=15)
a

array([11, 28, 27, 25, 11, 18, 14, 18, 13, 23, 12, 10, 18, 23, 11])

In [281]:
np.sort(a)

array([10, 11, 11, 11, 12, 13, 14, 18, 18, 18, 23, 23, 25, 27, 28])

In [283]:
a=np.random.randint(10,30,size=(3,4))
a

array([[19, 22, 18, 26],
       [28, 12, 17, 11],
       [22, 18, 29, 19]])

In [289]:
np.sort(a,axis=1)

array([[18, 19, 22, 26],
       [11, 12, 17, 28],
       [18, 19, 22, 29]])

In [287]:
np.sort(a,axis=0)

array([[19, 12, 17, 11],
       [22, 18, 18, 19],
       [28, 22, 29, 26]])

In [285]:
np.sort(a, axis=None)

array([11, 12, 17, 18, 18, 19, 19, 22, 22, 26, 28, 29])

### Numpy

# 3D Indexing

In [ ]:
import numpy as np
arr2 = np.array([[[1,2,7],[3,4,8],[5,6,9]],[[11,12,17],[13,14,18],[15,16,19]],[[10,2,70],[30,40,80],[50,60,90]]])
print("Dimensions of array",arr2.ndim)
print("shape",arr2.shape)
print(arr2)

In [ ]:
arr2[0,1,1]

In [ ]:
arr2[1,2,1]

In [ ]:
arr2[2,2,1]

In [ ]:
arr2[2,0,2]

In [ ]:
arr2[2,1,0]

In [ ]:
arr1 = np.array([4,5,6,7,8,9])
print(arr1)
print("Dimensions of array -->",arr1.ndim)

In [ ]:
arr1 = np.array([4,5,6,7,8,9],ndmin=5)
print(arr1)
print("Dimensions of array -->",arr1.ndim)

In [ ]:
arr1 = np.array([4,5,6,7,8,9],ndmin=20)
print(arr1)
print("Dimensions of array -->",arr1.ndim)

In [ ]:
arr1 = np.array([[4,5],[6,7],[8,9]], ndmin = 3)
print(arr1)
print("Dimensions of array -->",arr1.ndim)

In [ ]:
arr1 = np.array([[4,5],[6,7],[8,9]], ndmin = 1)
print(arr1)
print("Dimensions of array -->",arr1.ndim)

# Reshape Function

In [291]:
import numpy as np

In [297]:
arr=np.array([1,2,3,4,5,6])
reshaped_arr=arr.reshape((2,3))

In [295]:
arr=np.array([2,3,6,7,8,9,33,2,1,5,4,8])
arr1=arr1.reshape(4,3)
print(arr1)
print("Dimesion >>", arr1.ndim)
print("Shape >>", arr1.shape)

NameError: name 'arr1' is not defined

In [299]:
arr1 = np.array([1,2,3,4,5,6,10,20,30,40,50,60])

arr1 = arr1.reshape(4,3)
print(arr1)
print("Dimensions >>",arr1.ndim)
print("Shape -->",arr1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
Dimensions >> 2
Shape --> (4, 3)


In [301]:
arr1 = np.array([1,2,3,4,5,6,10,20,30,40,50,60])

arr1 = arr1.reshape(2,6)
print(arr1)
print("Dimensions >>",arr1.ndim)
print("Shape -->",arr1.shape)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]]
Dimensions >> 2
Shape --> (2, 6)


In [303]:
arr1 = np.array([1,2,3,4,5,6,10,20,30,40,50,60])

arr1 = arr1.reshape(6,2)
print(arr1)
print("Dimensions >>",arr1.ndim)
print("Shape -->",arr1.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10 20]
 [30 40]
 [50 60]]
Dimensions >> 2
Shape --> (6, 2)


In [305]:
arr1 = np.array([1,2,3,4,5,6,10,20,30,40,50,60])
print(arr1)
print("Dimensions >>",arr1.ndim)
print("Shape -->",arr1.shape)

[ 1  2  3  4  5  6 10 20 30 40 50 60]
Dimensions >> 1
Shape --> (12,)


In [307]:
arr1 = np.array([[1,2,3,4],[5,6,10,20],[30,40,50,60]])

arr1 = arr1.reshape(12,)
print(arr1)
print("Dimensions >>",arr1.ndim)
print("Shape -->",arr1.shape)


# Convert array into list
l1 = list(arr1)
l1

[ 1  2  3  4  5  6 10 20 30 40 50 60]
Dimensions >> 1
Shape --> (12,)


[1, 2, 3, 4, 5, 6, 10, 20, 30, 40, 50, 60]

In [309]:
a=np.array([[1,2,3,4],[5,6,7,8],[5,4,3,2]])
print(a)
l1=list(a)
print(l1)

[[1 2 3 4]
 [5 6 7 8]
 [5 4 3 2]]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([5, 4, 3, 2])]


In [311]:
a=np.array([[1,2,3,4],[5,6,7,8],[5,4,3,2]])
print(a)
l1=a.tolist()

print(l1)

[[1 2 3 4]
 [5 6 7 8]
 [5 4 3 2]]
[[1, 2, 3, 4], [5, 6, 7, 8], [5, 4, 3, 2]]


In [313]:
aa=([[4,5,6,7,8,2,3]])
aa

[[4, 5, 6, 7, 8, 2, 3]]

In [315]:
l1=aa.tolist()
l1

AttributeError: 'list' object has no attribute 'tolist'

In [317]:
l1=[3,4,5,6,7,8]
a=np.array(l1)
arr=a*2
result=arr.tolist()
result

[6, 8, 10, 12, 14, 16]

In [319]:
l1=[2,3,4,5,6]
a1=np.array(l1)
q=a1**2
s=q.tolist()
s

[4, 9, 16, 25, 36]

In [321]:
a1=np.array([3,4,5,6])
a2=np.array([6,7,8,3])
a1+a2

array([ 9, 11, 13,  9])

In [123]:
a1=np.array([3,4,5,6])
a2=np.array([6,7,8,3])
np.add(a1,a2)

array([ 9, 11, 13,  9])

In [125]:
a1=np.array([3,4,5,6])
a2=np.array([6,7,8,3])
a1*a2

array([18, 28, 40, 18])

In [131]:
a1=np.array([3,4,5,6])
a2=np.array([6,7,8,3])
np.multiply(a1,a2)

array([18, 28, 40, 18])

In [133]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sum(a1)

45

In [135]:
# Matrix Addition
a1=np.array([[10,20],[44,54]])
a2=np.array([[5,3],[8,9]])

np.add(a1,a2)

array([[15, 23],
       [52, 63]])

In [137]:
# Matrix Multiplication

a1=([[3,4],[5,7],[8,9]])
a2=([[6,7],[4,5],[3,2]])
print("Array1\n",a1)
print("Array2\n",a2)
np.multiply(a1,a2)

Array1
 [[3, 4], [5, 7], [8, 9]]
Array2
 [[6, 7], [4, 5], [3, 2]]


array([[18, 28],
       [20, 35],
       [24, 18]])

In [139]:
# dot product

a1=([[3,4],[5,7]])
a2=([[6,7],[4,5]])
print("Array1\n",a1)
print("Array2\n",a2)
np.dot(a1,a2)

Array1
 [[3, 4], [5, 7]]
Array2
 [[6, 7], [4, 5]]


array([[34, 41],
       [58, 70]])

In [141]:
a1=([[3,4],[5,7],[4,5]])
a2=([[6,7],[4,5]])
print("Array1\n",a1)
print("Array2\n",a2)
np.dot(a1,a2)

Array1
 [[3, 4], [5, 7], [4, 5]]
Array2
 [[6, 7], [4, 5]]


array([[34, 41],
       [58, 70],
       [44, 53]])

In [143]:
a1=([[3,4],[5,7],[4,5],[5,6]])
a2=([[6,7],[4,5],[3,4]])
print("Array1\n",a1)
print("Array2\n",a2)
np.dot(a1,a2)

Array1
 [[3, 4], [5, 7], [4, 5], [5, 6]]
Array2
 [[6, 7], [4, 5], [3, 4]]


ValueError: shapes (4,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [145]:
a1=np.array([[3,4],[5,7],[4,5]])
a2=np.array([[6,7],[4,5],[3,4]])
a3=np.array([[2,3],[4,2]])
np.dot(a1,a3)
np.dot(a3,a3)

array([[16, 12],
       [16, 16]])

# Stastistical Function

In [147]:
a=np.random.randint(3,9,size=5)
a

array([7, 4, 6, 8, 7])

In [149]:
np.mean(a)

6.4

In [151]:
v=np.random.randint(8,30,size=15)
v

array([16, 24,  8, 11, 13, 14, 13, 13, 16, 18,  9,  9, 18, 23, 20])

In [153]:
np.mean(v)

15.0

In [155]:
a=np.array([4,5,6,7])
np.median(a)

5.5

In [157]:
n=([3,4,8,3,2])
print(n)
np.median(n)

[3, 4, 8, 3, 2]


3.0

# 3. Std

In [159]:
arr=np.array([2,3,4,5,7,8,9,3,2,21,4,32,4,4,2,4,4,4,33])
arr

array([ 2,  3,  4,  5,  7,  8,  9,  3,  2, 21,  4, 32,  4,  4,  2,  4,  4,
        4, 33])

In [161]:
std=np.std(arr)
std

9.320397314180488

In [163]:
np.mean(arr)

8.157894736842104

In [165]:
var=np.var(arr)
var

86.86980609418283

In [167]:
from scipy import stats

In [168]:
mode=stats.mode(arr,keepdims=False)
mode[0]

4

# Liner Algebra Function

In [171]:
import numpy as np

In [173]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,6]])
np.multiply(A,B)

array([[ 5, 12],
       [21, 24]])

In [175]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,6]])
np.dot(A,B)

array([[19, 18],
       [43, 42]])

In [177]:
import numpy as np

In [ ]:
# Transpose matrix

In [179]:
A=np.array([[3,4],[5,6]])
B=np.array([15,20])
print("A--\n",A)
print("B---\n",B)

A--
 [[3 4]
 [5 6]]
B---
 [15 20]


In [181]:
np.linalg.solve(A,B)

array([-5. ,  7.5])

In [183]:
# Inverse

np.linalg.inv(A)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [185]:
A= np.array([[2,3,5],[3,-5,7],[4,2,10]])
B= np.array([10,15,30])

In [187]:
np.linalg.solve(A,B)

array([-110. ,   -2.5,   47.5])

In [189]:
np.linalg.inv(A)

array([[ 16.  ,   5.  , -11.5 ],
       [  0.5 ,  -0.  ,  -0.25],
       [ -6.5 ,  -2.  ,   4.75]])

In [191]:
C=np.array([[3,4],[5,6]])
D=np.array([21,32])
np.linalg.solve(C,D)

array([1. , 4.5])

In [193]:
np.linalg.inv(A)

array([[ 16.  ,   5.  , -11.5 ],
       [  0.5 ,  -0.  ,  -0.25],
       [ -6.5 ,  -2.  ,   4.75]])

# Natural log

In [323]:
print(np.log(1))
print(np.log(2))
print(np.log(3))
print(np.log(3.4))
print(np.log(100))
print(np.log(-0.3))
print(np.log(2.3))

0.0
0.6931471805599453
1.0986122886681098
1.2237754316221157
4.605170185988092
nan
0.8329091229351039


C:\Users\Admin\AppData\Local\Temp\ipykernel_17316\1556378643.py:6: RuntimeWarning: invalid value encountered in log
  print(np.log(-0.3))


In [325]:
a=np.random.randint(10,20,size=10)
a

array([12, 10, 13, 19, 18, 15, 17, 19, 17, 17])

In [327]:
print(np.log(a))

[2.48490665 2.30258509 2.56494936 2.94443898 2.89037176 2.7080502
 2.83321334 2.94443898 2.83321334 2.83321334]


# log to the base 10

In [329]:
print(np.log10(1))
print(np.log10(2))
print(np.log10(3))
print(np.log10(3.4))
print(np.log10(100))
print(np.log10(2.3))

0.0
0.3010299956639812
0.47712125471966244
0.5314789170422551
2.0
0.36172783601759284


In [331]:
s=np.random.randint(30,50,size=15)
s

array([44, 30, 49, 49, 38, 44, 30, 32, 33, 40, 37, 34, 41, 38, 46])

In [333]:
print(np.log10(s))

[1.64345268 1.47712125 1.69019608 1.69019608 1.5797836  1.64345268
 1.47712125 1.50514998 1.51851394 1.60205999 1.56820172 1.53147892
 1.61278386 1.5797836  1.66275783]


# log to the base 2

In [335]:
print(np.log2(1))
print(np.log2(2))
print(np.log2(3))
print(np.log2(3.4))
print(np.log2(100))
print(np.log2(2.3))

0.0
1.0
1.584962500721156
1.765534746362977
6.643856189774724
1.2016338611696504


In [337]:
d=np.random.randint(80,100,size=10)
d

array([82, 96, 98, 94, 90, 90, 85, 90, 88, 84])

In [339]:
print(np.log2(d))

[6.357552   6.5849625  6.61470984 6.55458885 6.4918531  6.4918531
 6.40939094 6.4918531  6.45943162 6.39231742]


# Log Transformation

In [341]:
a=np.array([1,2,3,4,5,6,899,544,800,6544])
a

array([   1,    2,    3,    4,    5,    6,  899,  544,  800, 6544])

In [343]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 6.80128303, 6.29894925, 6.68461173, 8.78630388])

In [345]:
a=np.random.randint(10,20,size=10)
a

array([18, 18, 19, 16, 15, 19, 11, 19, 14, 16])

In [347]:
np.log(a)

array([2.89037176, 2.89037176, 2.94443898, 2.77258872, 2.7080502 ,
       2.94443898, 2.39789527, 2.94443898, 2.63905733, 2.77258872])

# statstics Operation

In [402]:
a=np.array([1,3,5,5,4,3,2,6,7,7,7,8,9,54,5,6,7,7,7,7,8,8,8,])
a

array([ 1,  3,  5,  5,  4,  3,  2,  6,  7,  7,  7,  8,  9, 54,  5,  6,  7,
        7,  7,  7,  8,  8,  8])

In [404]:
np.mean(a)

8.0

In [406]:
np.median(a)

7.0

In [410]:
np.std(a)

10.02171555217447

In [408]:
np.var(a)

100.43478260869566

In [412]:
from scipy import stats

In [414]:
mode=stats.mode(a,keepdims=False)
mode[0]

7

In [416]:
np.pi

3.141592653589793

In [418]:
import numpy as np

In [420]:
np.pi

3.141592653589793

In [422]:
np.sin(np.pi/3)

0.8660254037844386

In [424]:
np.cos(np.pi/3)

0.5000000000000001

In [426]:
tan45=(np.pi/6)
print(tan45)

0.5235987755982988


In [ ]:
sin=opp/hyp
cos=adj/hyp
tan=opp/hyp

In [430]:
sin30=(np.pi/6)
sin30

0.5235987755982988

In [432]:
sin45=(np.pi/4)
sin45

0.7853981633974483

In [434]:
sin45=(np.pi/4)
sin45

0.7853981633974483

In [436]:
sin30=np.pi/6
sin30

0.5235987755982988

# Convert into degree into radian

In [438]:
a=np.array(([0,30,45,60,90,180]))
degree=np.deg2rad(a)
degree

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265])

In [440]:
c=np.array([[0,30,45,60]])
radian=np.deg2rad(c)
radian

array([[0.        , 0.52359878, 0.78539816, 1.04719755]])

# radian to degree convertre

In [442]:
s=np.array([[0.        , 0.52359878, 0.78539816, 1.04719755]])
degree=np.rad2deg(s)
print(degree)

[[ 0.         30.00000025 44.99999981 59.99999993]]


In [444]:
s=np.array([[0.        , 0.52359878, 0.78539816, 1.04719755]])
sin_values=np.sin(s)
print(sin_values)

[[0.         0.5        0.70710678 0.8660254 ]]


In [446]:
s=np.array([[0.        , 0.52359878, 0.78539816, 1.04719755]])
cos_values=np.cos(s)
print(cos_values)

[[1.         0.8660254  0.70710678 0.5       ]]


In [448]:
s=np.array([[0.        , 0.52359878, 0.78539816, 1.04719755]])
tan_values=np.tan(s)
print(tan_values)

[[0.         0.57735028 0.99999999 1.7320508 ]]


# Append

In [396]:
arr1  = np.array([1,2,3,4,5])
arr2 =np.array(200)
arr3 =np.array([10,30,43,22,44])
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
200
[10 30 43 22 44]


In [398]:
np.append(arr1,arr3)

array([ 1,  2,  3,  4,  5, 10, 30, 43, 22, 44])

In [400]:
np.append(arr2,arr3)

array([200,  10,  30,  43,  22,  44])

# Flatting the array

In [390]:
arrr1=np.array([[2,3],[4,5]])
arr2=np.array([[5,3],[6,4]])
print("array1 ===\n",arrr1)
print("array2 ==\n",arr2)

a=np.append(arrr1,arr2)
a

array1 ===
 [[2 3]
 [4 5]]
array2 ==
 [[5 3]
 [6 4]]


array([2, 3, 4, 5, 5, 3, 6, 4])

# Adding 2 rows

In [384]:
arrr1=np.array([[2,3],[4,5]])
arr2=np.array([[5,3],[6,4]])
print("array1-->\n", arrr1)
print("array2-->\n",arr2)

array1-->
 [[2 3]
 [4 5]]
array2-->
 [[5 3]
 [6 4]]


In [386]:
arr=np.append(arrr1,arr2,axis=0)   # rowsise
arr

array([[2, 3],
       [4, 5],
       [5, 3],
       [6, 4]])

In [388]:
arr=np.append(arrr1,arr2,axis=1)    # column wise
arr

array([[2, 3, 5, 3],
       [4, 5, 6, 4]])

# Concstenate()

In [378]:
a23= np.array([[2,3],[4,5]])
a34=np.array([[6,7],[8,9]])
np.concatenate([a23,a34],axis=0)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [380]:
a23= np.array([[2,3],[4,5]])
a34=np.array([[6,7],[8,9]])
np.concatenate([a23,a34],axis=1)

array([[2, 3, 6, 7],
       [4, 5, 8, 9]])

In [450]:
array1 = np.array([3,2,4,5])
array2 = np.array([10,20,30,40])

np.concatenate([array1, array2], axis = 1)  # !D arrays we can not concatenate

AxisError: axis 1 is out of bounds for array of dimension 1

# 1 for loop

In [376]:
array=np.array([1,2,3,4])
for i in array:
    print("value is--",i)

value is-- 1
value is-- 2
value is-- 3
value is-- 4


In [374]:
aa=np.array([[1,2],[3,4],[6,7]])
for i in aa:
    for j in i:
        print("value is--", j)

value is-- 1
value is-- 2
value is-- 3
value is-- 4
value is-- 6
value is-- 7


In [372]:
aa=np.array([[1,2],[3,4],[6,7]])
for i in aa:
    print("value is-->",i)

value is--> [1 2]
value is--> [3 4]
value is--> [6 7]


In [370]:
aa=np.array([[[1,2],[3,4],[6,7]],[[3,4],[6,7],[3,2]]])
for i in aa:
    for j in i:
        for k in j:
            print("value is-->",i)

value is--> [[1 2]
 [3 4]
 [6 7]]
value is--> [[1 2]
 [3 4]
 [6 7]]
value is--> [[1 2]
 [3 4]
 [6 7]]
value is--> [[1 2]
 [3 4]
 [6 7]]
value is--> [[1 2]
 [3 4]
 [6 7]]
value is--> [[1 2]
 [3 4]
 [6 7]]
value is--> [[3 4]
 [6 7]
 [3 2]]
value is--> [[3 4]
 [6 7]
 [3 2]]
value is--> [[3 4]
 [6 7]
 [3 2]]
value is--> [[3 4]
 [6 7]
 [3 2]]
value is--> [[3 4]
 [6 7]
 [3 2]]
value is--> [[3 4]
 [6 7]
 [3 2]]


#  2 nditer

In [ ]:
import numpy as np

In [368]:
array=np.array([[4,3],[5,6],[7,8],[5,7]])

for i in np.nditer(array):
    print("value is-->",i)

value is--> 4
value is--> 3
value is--> 5
value is--> 6
value is--> 7
value is--> 8
value is--> 5
value is--> 7


# 3 ndenumerate

In [366]:
array=np.array([[3,2],[7,6],[8,9],[6,6]])

for i in np. ndenumerate(array):
    print("value is --",i)

value is -- ((0, 0), 3)
value is -- ((0, 1), 2)
value is -- ((1, 0), 7)
value is -- ((1, 1), 6)
value is -- ((2, 0), 8)
value is -- ((2, 1), 9)
value is -- ((3, 0), 6)
value is -- ((3, 1), 6)


In [364]:
print(np.ceil(2.3))
print(np.ceil(1.4))
print(np.ceil(3.66))
print(np.ceil(7.8))

3.0
2.0
4.0
8.0


In [362]:
np.ceil([[3.4],[7.8],[9.0]])

array([[4.],
       [8.],
       [9.]])

In [358]:
rray = np.array([[[2.50,3.88],[4.76,5.48],[6.14,7.87]], [[20.45,30.48],[40.14,50.74],[60.97,70.47]]])

np.ceil(rray)

array([[[ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.]],

       [[21., 31.],
        [41., 51.],
        [61., 71.]]])

# 4. np.floor

In [360]:
np.floor([[3.4],[7.8],[9.0]])

array([[3.],
       [7.],
       [9.]])

In [356]:
print(np.floor(4.6))
print(np.floor(3.5))
print(np.floor(2.3))
print(np.floor(1.2))
print(np.floor(1.002))

4.0
3.0
2.0
1.0
1.0


In [353]:
array = np.array([[[2.50,3.88],[4.76,5.48],[6.14,7.87]], [[20.45,30.48],[40.14,50.74],[60.97,70.47]]])

np.floor(array)

array([[[ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[20., 30.],
        [40., 50.],
        [60., 70.]]])

# 5 np.around

In [349]:
np.around(2.4356789)

2.0

In [351]:
np.around(21.4954458)

21.0

# 6 np.where

In [73]:
l1 = [2,3,4,5,6,7,4,5,6,4,7]

index = [i for i, v in enumerate(l1) if v == 4]
index

[2, 6, 9]

In [75]:
q = [1,2,3,4,5,6,7]

index = [i for i, v in enumerate(q) if v == 7]
index

[6]

In [452]:
q=[2,3,4,5,6,7,4,5,6,4,7]

index = [i for i, v in enumerate(q) if v == 7]
index

[5, 10]

In [462]:
b1= [2,3,4,5,6,78]
array=np.array(l1)

index=np.where(array==4)
print(index[0])

[2]


In [468]:
l1 = [2,3,4,5,6,7,4,5,6,4,7]

array=np.array(l1)

index=np.where(array<=4)
print(index[0])

[0 1 2 6 9]


# 7. np.delete

In [475]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [479]:
np.delete(array,1)

array([2, 4, 5, 6, 7, 4, 5, 6, 4, 7])

In [491]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [493]:
np.delete(arr,[3,5])

array([1, 2, 3, 5, 7, 8, 9])

In [497]:
arr1=np.array([4,3,2,1,6,5,4,8,7,6])
np.delete(arr1,[7,6])

array([4, 3, 2, 1, 6, 5, 7, 6])

# 8.np.max  , np.min

In [500]:
arr1=np.array([2,4,5,6,7,8,999,33])
arr1

array([  2,   4,   5,   6,   7,   8, 999,  33])

In [502]:
np.max(arr1)

999

In [509]:
np.min(arr1)

2

In [504]:
arr=np.random.randint(10,50,size=25)
arr

array([46, 27, 49, 35, 17, 40, 24, 42, 15, 42, 10, 49, 13, 48, 28, 22, 14,
       11, 11, 35, 42, 36, 19, 42, 19])

In [506]:
np.max(arr)

49

In [511]:
np.min(arr)

10

# 9.np.maximum()  , np.minimum()

In [518]:
a=np.array([23,44,65])
b=np.array([444,999,666])


In [520]:
np.minimum(a,b)

array([23, 44, 65])

In [522]:
np.maximum(a,b)

array([444, 999, 666])

# 10.np.sort()

In [538]:
arr11=np.array([7,44,3,3,6,777,55,33,2222])

In [540]:
np.sort(arr11)

array([   3,    3,    6,    7,   33,   44,   55,  777, 2222])

In [542]:
arr=np.random.randint(20,40,size=10)
arr11

array([   7,   44,    3,    3,    6,  777,   55,   33, 2222])

In [544]:
np.sort(arr11)

array([   3,    3,    6,    7,   33,   44,   55,  777, 2222])

In [553]:
arr21=np.random.randint(20,40,size=(2,3))
arr21

array([[35, 20, 30],
       [21, 34, 28]])

# 11.-np.sort(-array)

In [546]:
-np.sort(-arr11)

array([2222,  777,   55,   44,   33,    7,    6,    3,    3])

In [555]:
-np.sort(-arr21)

array([[35, 30, 20],
       [34, 28, 21]])

# 12.np.square()

In [565]:
array = np.array([5,6,7,8,9,10])
array

array([ 5,  6,  7,  8,  9, 10])

In [571]:
np.square(array)

array([ 25,  36,  49,  64,  81, 100])

# 13.np.sqrt()

In [573]:
array = np.array([5,6,7,8,9,10])
array

array([ 5,  6,  7,  8,  9, 10])

In [576]:
np.sqrt(array)   # square root transformation

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

# 14.flatten()

In [579]:
a=np.array([[2,3,4],[5,4,2],[9,4,3]])
a

array([[2, 3, 4],
       [5, 4, 2],
       [9, 4, 3]])

In [581]:
a.flatten()

array([2, 3, 4, 5, 4, 2, 9, 4, 3])

In [583]:
array = np.array([[[2,3,4],[5,6,7],[8,9,10]], [[12,13,14],[15,16,17],[18,19,110]]])
array.flatten()

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  13,  14,  15,
        16,  17,  18,  19, 110])

In [587]:
arr=np.array([[1,2,3],[4,3,2],[5,4,6]])
x=arr.tolist()
print(x,type(x))

[[1, 2, 3], [4, 3, 2], [5, 4, 6]] <class 'list'>


# 15.ravel()

In [590]:
array = np.array([[2,3,4],[5,6,7],[8,9,10]])

a = array.ravel()

a[2] = 400

In [592]:
print("*"*40)
print(a)

****************************************
[  2   3 400   5   6   7   8   9  10]


In [594]:
print("-"*40)

print(array)

----------------------------------------
[[  2   3 400]
 [  5   6   7]
 [  8   9  10]]


# 16.np.full() 

In [597]:
np.full([4,2],100)

array([[100, 100],
       [100, 100],
       [100, 100],
       [100, 100]])

# 17. np.power()

In [600]:
array=np.array([4,2,3,6,7,4,3])
array

array([4, 2, 3, 6, 7, 4, 3])

In [602]:
np.power(array,3)

array([ 64,   8,  27, 216, 343,  64,  27], dtype=int32)